version: '3.8'
services:
  db:
    image: mysql:oracle
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: 'America/Sao_Paulo'
    volumes:
      - mysql-db:/var/lib/mysql
    restart: always
    env_file:
      - .env

volumes:
  mysql-db:
