version: '3.8'

services:
  api:
    build: .
    container_name: sdto-api
    ports:
      - 3000:3001
    depends_on:
      - db
    volumes:
      - '.:/app/'
      - '/app/src/node_modules'
    restart: unless-stopped
    networks:
      - sdto-network
    env_file:
      - ./.env
    entrypoint: ["./entrypoint.sh"]

  db:
    image: mysql:oracle
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: 'America/Sao_Paulo'
    volumes:
      - mysql-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - sdto-network
    env_file:
      - ./.env

networks:
  sdto-network:

volumes:
  mysql-db:
