version: '3.8'
services:
  db:
    image: mysql:oracle
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sdtodb
      MYSQL_USER: sdto
      MYSQL_PASSWORD: sdto@pass
      TZ: 'America/Sao_Paulo'
    volumes:
      - mysql-db:/var/lib/mysql
    restart: always
    env_file:
      - .env

volumes:
  mysql-db:
